In [30]:

import numpy as np

# 1. STANDARD CASE

###################################################
##### Compute C, A, Aij_minus_kikj2 ###############
###################################################

##### compute C
#z=np.array([0,0,0,1,1])
z=np.array([0,0,0,1,1])
g=len(np.unique(z))
Z=np.mat(np.zeros((len(z),g)))
for k in np.arange(g) :
    indices=np.where(z==k)[0]
    Z[indices,k]=1
C_temp=Z * Z.T    
diag_C=np.diag(np.diag(C_temp))
C=C_temp - diag_C           # do not take loops into account  ; C is a numpy matrix    
###### A_ij
A=np.zeros((5,5))
A[1,0]=1. ; A[0,1]=1. ; A[2,0]=1. ; A[0,2]=1. ; A[1,2]=1. ; A[2,1]=1. ; A[3,4]=1. ; A[4,3]=1.
m=float(A.sum()/2)
print(A)
###### (k_i * k_j ) / 2m
k_i=np.matrix(A.sum(axis=0))
kikj2m=(k_i.T * k_i) / (2. *m)

#####  A_ij - (  (k_i * k_j ) / 2m) )
Aij_minus_kikj2m= A - kikj2m         # Aij_minus_kikj2 is a numpy matrix


###################################################
##### Compute mod. and corr. coeff. ###############
###################################################

##### modularity: first version

mod1=(np.trace(Aij_minus_kikj2m * C ) ) / (2. *m)
print("mod:" , mod1)

##### modularity: another version

mod2=np.sum(np.multiply(Aij_minus_kikj2m , C) ) / (2. *m)
print("mod:" , mod2)

##### correlation coeff. (normalized mod.)

max_val=( (2 * m) - np.sum(np.multiply(kikj2m , C) ) ) / (2. *m)
norm_mod=mod1  / max_val
print("norm. mod.:" ,norm_mod)



# 2. BIPARTITE CASE

###################################################
##### Compute C, A, Aij_minus_kikj2 ###############
###################################################

z=np.array([0,0,0,1,1])
w=np.array([0,0,1,1])
g=len(np.unique(z))
m=len(np.unique(w))

Z=np.mat(np.zeros((len(z),g)))
for k in np.arange(g) :
    indices=np.where(z==k)[0]
    Z[indices,k]=1
    
W=np.mat(np.zeros((len(w),m)))
for k in np.arange(m) :
    indices=np.where(w==k)[0]
    W[indices,k]=1

C=Z * W.T  
print(C)

A=np.zeros((len(z),len(w)))
A[0,0]=1. ; A[0,1]=1. ; A[1,0]=1. ; A[1,1]=1. ; A[2,0]=1. ; A[2,1]=1. ; A[3,2]=1. ; A[3,3]=1.
A[4,2]=1.;  A[4,3]=1.
print(A)

N=float(np.sum(A) ) # nb edges
print(N)

###### (k_i * k_j ) / 2m
k_i=np.matrix(A.sum(axis=1))
k_j=np.matrix(A.sum(axis=0))

kikj2m=k_i.T.dot(k_j) / N

#####  A_ij - (  (k_i * k_j ) / 2m) )
Aij_minus_kikj2m= A - kikj2m         # Aij_minus_kikj2 is a numpy matrix

###################################################
##### Compute mod. and corr. coeff. ###############
###################################################

##### modularity

mod1=(np.trace(Aij_minus_kikj2m.T * C ) ) / N
print("mod. bipart. :" , mod1)

##### normalized coeff.
max_val=( N  - np.sum(np.multiply(kikj2m , C) ) ) / N
norm_mod=mod1  / max_val
print("norm. mod.:" ,norm_mod)


# 3. DIRECTED CASE

###################################################
##### Compute C, A, Aij_minus_kikj2 ###############
###################################################

##### compute C
#z=np.array([0,0,0,1,1])
z=np.array([0,0,0,1,1,1])
g=len(np.unique(z))
Z=np.mat(np.zeros((len(z),g)))
for k in np.arange(g) :
    indices=np.where(z==k)[0]
    Z[indices,k]=1
C_temp=Z * Z.T    
diag_C=np.diag(np.diag(C_temp))
C=C_temp - diag_C 

###### A_ij  ;  j --> i
A=np.zeros((len(z), len(z)))
A[1,0]=1. ; A[0,1]=1.  # ;  A[2,0]=1. ; A[0,2]=1. ; A[1,2]=1. ;  A[2,1]=1. ; A[3,4]=1.  ; A[4,3]=1. ;  A[4,5]=1. 
m=float(A.sum())
print("A")
print(A)

###### (k_i * k_j ) / 2m

k_in=np.matrix(A.sum(axis=1))
k_out=np.matrix(A.sum(axis=0))

print("k_in")
print(k_in)

print("k_out")
print(k_out)

print("k_in / m).T")
print((k_in / m).T)

kikjbym=(k_in / m).T.dot(k_out) # sum(k_in) = m = sum(k_out)
print("kikjbym")
print(kikjbym)

#####  A_ij - (  (k_i * k_j ) / m) )
Aij_minus_kikjbym= A - kikjbym         #   Aij_minus_kikjbym is a numpy matrix

print("Aij_minus_kikjbym")
print(Aij_minus_kikjbym)
###################################################
##### Compute mod. and corr. coeff. ###############
###################################################

##### modularity: first version

mod1=(np.trace(Aij_minus_kikjbym * C ) ) / m
print("mod:" , mod1)

##### modularity: another version

mod2=np.sum(np.multiply(Aij_minus_kikjbym , C) ) / m
print("mod:" , mod2)

##### correlation coeff. (normalized mod.)

max_val=( m - np.sum(np.multiply(kikjbym , C) ) ) / m
norm_mod=mod1  / max_val
print("norm. mod.:" ,norm_mod)



[[ 0.  1.  1.  0.  0.]
 [ 1.  0.  1.  0.  0.]
 [ 1.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.]
 [ 0.  0.  0.  1.  0.]]
mod: 0.59375
mod: 0.59375
norm. mod.: 1.0
[[ 1.  1.  0.  0.]
 [ 1.  1.  0.  0.]
 [ 1.  1.  0.  0.]
 [ 0.  0.  1.  1.]
 [ 0.  0.  1.  1.]]
[[ 1.  1.  0.  0.]
 [ 1.  1.  0.  0.]
 [ 1.  1.  0.  0.]
 [ 0.  0.  1.  1.]
 [ 0.  0.  1.  1.]]
10.0
mod. bipart. : 0.48
norm. mod.: 1.0
A
[[ 0.  1.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]
k_in
[[ 1.  1.  0.  0.  0.  0.]]
k_out
[[ 1.  1.  0.  0.  0.  0.]]
k_in / m).T
[[ 0.5]
 [ 0.5]
 [ 0. ]
 [ 0. ]
 [ 0. ]
 [ 0. ]]
kikjbym
[[ 0.5  0.5  0.   0.   0.   0. ]
 [ 0.5  0.5  0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0. ]]
Aij_minus_kikjbym
[[-0.5  0.5  0.   0.   0.   0. ]
 [ 0.5 -0.5  0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.

In [ ]:
# AZURE - F. ROLE   https://azure.microsoft.com/en-us/documentation/articles/cloud-services-python-how-to-use-service-management/

import json
from azure import *
from azure.servicemanagement import *

# First  create a management certificate, and upload the .cer file to Azure.
# `openssl req -x509 -nodes -days 365 -newkey rsa:1024 -keyout mycert.pem -out mycert.pem`
# `openssl x509 -inform pem -in mycert.pem -outform der -out mycert.cer`
# to upload: https://azure.microsoft.com/en-us/documentation/articles/azure-ap

with open("../conf.json") as f:
    o=json.load(f)
subscription_id = o['s_id']
certificate_path =  o['c_path']  # the .pem certificate

print(subscription_id) ; print(certificate_path)

sms = ServiceManagementService(subscription_id, certificate_path)

result = sms.list_locations()
for location in result:
    print(location.name)
    
sms.start_role("xxx", "xxx", "xxx")


#  start_role(service_name, deployment_name, role_name)[source]  Starts the specified virtual machine
#  role-name is the nale of the VM  ; for deployment_name see http://stackoverflow.com/questions/33106731/azure-find-deployment-name
# Click on the cloud service associated with your Virtual Machine and then go to dashboard. You will see the deployment name on the right hand side as shown in the screenshot below.

Scalar attribute

In [47]:
max_val=( (2 * m) - np.sum(np.multiply(kikj2m , C) ) ) / (2. *m)

print(covariance)
norm_mod=covariance  / max_val
print(norm_mod)
#print(np.sum(np.multiply(A ,C)))
#print(m)

covariance2=(np.trace(Aij_minus_kikj2m * C ) ) / (2. *m)
print(covariance2)





import numpy as np

##### compute

x_i=np.matrix([3,60,2,5,5]) # attributes of node i
xixj=x_i.T * x_i

###### A_ij
A=np.zeros((5,5) )
A[1,0]=1. ; A[0,1]=1. ; A[2,0]=1. ; A[0,2]=1. ; A[1,2]=1. ; A[2,1]=1. ; A[3,4]=1. ; A[4,3]=1.
m=A.sum()/2
print(A)
###### (k_i * k_j ) / 2m
k_i=np.matrix(A.sum(axis=0))
kikj2m=k_i.T.dot(k_i) / (2. *m)

#####  A_ij - (  (k_i * k_j ) / 2m) )
Aij_minus_kikj2m= A - kikj2m

##### covariance, max ###########
covariance=np.sum(np.multiply(Aij_minus_kikj2m , xixj) ) / (2. *m)
max_val= ( np.sum(np.multiply(A,np.multiply(x_i.T,x_i.T)) ) - np.sum(np.multiply(kikj2m , xixj) ) )/ (2. *m)
print(covariance / max_val)

# compute delta
#xixi=np.multiply(x_i.T,x_i.T)
#difference=xixj - xixi
#print(difference)
#equal_indices=np.where(difference==0)
#delta_ij=np.zeros((A.shape[0],A.shape[1]))
#delta_ij[equal_indices]=1



[[ 0.  1.  1.  0.  0.]
 [ 1.  0.  1.  0.  0.]
 [ 1.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.]
 [ 0.  0.  0.  1.  0.]]
-0.370493162039
