In [34]:
import numpy as np

##### compute C
#z=np.array([0,0,0,1,1])
z=np.array([0,0,0,1,1])
g=len(np.unique(z))
Z=np.mat(np.zeros((len(z),g)))
for k in np.arange(g) :
    indices=np.where(z==k)[0]
    Z[indices,k]=1
C_temp=Z * Z.T    
diag_C=np.diag(np.diag(C_temp))
C=C_temp - diag_C           # do not take loops into account      
###### A_ij
A=np.zeros((5,5))
A[1,0]=1. ; A[0,1]=1. ; A[2,0]=1. ; A[0,2]=1. ; A[1,2]=1. ; A[2,1]=1. ; A[3,4]=1. ; A[4,3]=1.
m=A.sum()/2
print(A)
###### (k_i * k_j ) / 2m
k_i=np.matrix(A.sum(axis=0))
kikj2m=k_i.T.dot(k_i) / (2. *m)

#####  A_ij - (  (k_i * k_j ) / 2m) )
Aij_minus_kikj2m= A - kikj2m

##### covariance, max, normalized modularity ###########

covariance=np.sum(np.multiply(Aij_minus_kikj2m , C) ) / (2. *m)

max_val=( (2 * m) - np.sum(np.multiply(kikj2m , C) ) ) / (2. *m)

print(covariance)
norm_mod=covariance  / max_val
print(norm_mod)
#print(np.sum(np.multiply(A ,C)))
#print(m)



[[ 0.  1.  1.  0.  0.]
 [ 1.  0.  1.  0.  0.]
 [ 1.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.]
 [ 0.  0.  0.  1.  0.]]
0.59375
1.0


Scalar attribute

In [47]:
import numpy as np

##### compute

x_i=np.matrix([3,60,2,5,5]) # attributes of node i
xixj=x_i.T * x_i

###### A_ij
A=np.zeros((5,5) )
A[1,0]=1. ; A[0,1]=1. ; A[2,0]=1. ; A[0,2]=1. ; A[1,2]=1. ; A[2,1]=1. ; A[3,4]=1. ; A[4,3]=1.
m=A.sum()/2
print(A)
###### (k_i * k_j ) / 2m
k_i=np.matrix(A.sum(axis=0))
kikj2m=k_i.T.dot(k_i) / (2. *m)

#####  A_ij - (  (k_i * k_j ) / 2m) )
Aij_minus_kikj2m= A - kikj2m

##### covariance, max ###########
covariance=np.sum(np.multiply(Aij_minus_kikj2m , xixj) ) / (2. *m)
max_val= ( np.sum(np.multiply(A,np.multiply(x_i.T,x_i.T)) ) - np.sum(np.multiply(kikj2m , xixj) ) )/ (2. *m)
print(covariance / max_val)

# compute delta
#xixi=np.multiply(x_i.T,x_i.T)
#difference=xixj - xixi
#print(difference)
#equal_indices=np.where(difference==0)
#delta_ij=np.zeros((A.shape[0],A.shape[1]))
#delta_ij[equal_indices]=1



[[ 0.  1.  1.  0.  0.]
 [ 1.  0.  1.  0.  0.]
 [ 1.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.]
 [ 0.  0.  0.  1.  0.]]
-0.370493162039


In [ ]:



=np.matrix([-3,-3,50,50]) # attributes of node i
xixj=x_i.T * x_i

###### A_ij
A=np.zeros((4,4))
A[1,0]=1. ; A[0,1]=1. ; A[2,3]=1. ; A[3,2]=1.
m=A.sum()/2

###### (k_i * k_j ) / 2m
k_i=np.matrix(A.sum(axis=0))
kikj2m=k_i.T.dot(k_i) / (2. *m)

#####  A_ij - (  (k_i * k_j ) / 2m) )
Aij_minus_kikj2m= A - kikj2m


##### covariance ###########

covariance=np.sum(np.multiply(Aij_minus_kikj2m , xixj) ) / (2. *m)

##### assortativity coefficient ###########

# compute delta
xixi=np.multiply(x_i.T,x_i.T)
difference=xixj - xixi
print(difference)
equal_indices=np.where(difference==0)
delta_ij=A=np.zeros((A.shape[0],A.shape[1]))
delta_ij[equal_indices]=1


ki_times_delta_ij = np.multiply(delta_ij ,k_i.T )
ki_times_delta_ij_minus_kikj2m = ki_times_delta_ij - kikj2m
denominator=np.sum(np.multiply(ki_times_delta_ij_minus_kikj2m , xixj) ) / (2. *m)

r=covariance / denominator
r

#kikj2m_times_xixj= np.multiply(kikj2m ,xixj)
#kikj2m_times_xixj


In [57]:
import numpy as np

x_i=np.matrix([-3,-3,50,50]) # attributes of node i
xixj=x_i.T * x_i

###### A_ij
A=np.zeros((4,4))
A[1,0]=1. ; A[0,1]=1. ; A[2,3]=1. ; A[3,2]=1.
m=A.sum()/2

###### (k_i * k_j ) / 2m
k_i=np.matrix(A.sum(axis=0))
kikj2m=k_i.T.dot(k_i) / (2. *m)

#####  A_ij - (  (k_i * k_j ) / 2m) )
Aij_minus_kikj2m= A - kikj2m


##### covariance ###########

covariance=np.sum(np.multiply(Aij_minus_kikj2m , xixj) ) / (2. *m)

##### assortativity coefficient ###########

# compute delta
xixi=np.multiply(x_i.T,x_i.T)
difference=xixj - xixi
print(difference)
equal_indices=np.where(difference==0)
delta_ij=A=np.zeros((A.shape[0],A.shape[1]))
delta_ij[equal_indices]=1


ki_times_delta_ij = np.multiply(delta_ij ,k_i.T )
ki_times_delta_ij_minus_kikj2m = ki_times_delta_ij - kikj2m
denominator=np.sum(np.multiply(ki_times_delta_ij_minus_kikj2m , xixj) ) / (2. *m)

r=covariance / denominator
r

#kikj2m_times_xixj= np.multiply(kikj2m ,xixj)
#kikj2m_times_xixj


[[    0     0  -159  -159]
 [    0     0  -159  -159]
 [-2650 -2650     0     0]
 [-2650 -2650     0     0]]
[[ 1.  1.  0.  0.]
 [ 1.  1.  0.  0.]
 [ 0.  0.  1.  1.]
 [ 0.  0.  1.  1.]]


0.35888590775520635